project:
  type: default
format:
  revealjs:
    theme: [simple, ../../../assets/uefs.scss]
    css: ../../../assets/custom.css
    width: 1280
    height: 720
    transition: slide
    background-transition: fade
    preview-links: auto
    slide-number: true
    controls: true
    embed-resources: true
    logo: ../../../assets/logo-uefs.webp
    footer: "UEFS — Introdução à Estatística"